language:
    - python
python:
    - "2.7"
    - "3.6"

cache:
  pip: true
  bundler: true
  directories:
    - /tmp/dcase_util_datasets

notifications:
  email: false

before_install:
    - "sudo apt-get install -qq python-scipy"
    - "sudo apt-get install libav-tools"

# command to install dependencies
install:
    - "pip install scikit-learn==0.20.3"
    - "pip install -r requirements.txt"
    - "pip install python-coveralls"
    - "pip install coveralls"
    - "pip install nose"
    - "pip install librosa"
    - "pip install ipython"
    - "python setup.py develop"

# command to run tests
script:
    - "travis_wait nosetests --with-coverage --cover-erase --nocapture --cover-package=dcase_util -v -w tests/"

after_success:
    - "coveralls"
    - "python setup.py develop --uninstall"

after_failure:
    - "python setup.py develop --uninstall"